NumPy

NumPy (Numerical Python) is a Python library that focuses on scientific computing. NumPy has the ability to create N-dimensional array objects, which are similar to lists in Python. The advantage of NumPy arrays compared to lists in Python is that they consume less memory and run time faster. NumPy also makes it easier for us in Linear Algebra, especially operations on Vectors (1-d arrays) and Matrix (2-d arrays).

In [20]:
# Import NumPy

import numpy as np

In [21]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [24]:
# creating a NumPy array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [23]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Use a tuple to create a NumPy array

import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


TASK 1

In [6]:
# Import NumPy

import numpy as af

In [7]:
# Checking Numpy Version

print(af.__version__)

1.24.3


In [9]:
# creating a NumPy array

nilai = af.array([1.5, 2, 3.5, 4, 4.5])
print(nilai)

[1.5 2.  3.5 4.  4.5]


In [10]:
import numpy as af

nilai = af.array([1.5,2,3.5,4,4.5])

print(nilai)

print(type(nilai))

[1.5 2.  3.5 4.  4.5]
<class 'numpy.ndarray'>


Dimensions in Arrays

A dimension in arrays is one on level of array dapth (nested arrays) 

In [1]:
# 0-D Arrays

In [19]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
# Create a 1-D array

In [20]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [ ]:
# Create a 2-D array

In [23]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


TASK 2

In [28]:
import numpy as np

nilai = np.array(100)

print(nilai)

100


In [26]:
import numpy as np

hasil = np.array([1.5,2,'tiga',4,4.5])

print(hasil)

['1.5' '2' 'tiga' '4' '4.5']


In [27]:
import numpy as np

objek = np.array([[1.5,3.5,4.5], ['satu', 'dua', 'tiga'], [4, 5, 6]])

print(objek)

[['1.5' '3.5' '4.5']
 ['satu' 'dua' 'tiga']
 ['4' '5' '6']]


In [26]:
# Create a 3-D array with two 2-D arrays, both containing two arrays

In [25]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
import numpy as np

item = np.array([[[1.5,3.5,4.5], ['satu', 'dua', 'tiga']], [[4, 5, 6], [7, 13, 15]]])

print(item)

[[['1.5' '3.5' '4.5']
  ['satu' 'dua' 'tiga']]

 [['4' '5' '6']
  ['7' '13' '15']]]


In [ ]:
# Check how many dimensions the arrays have

In [4]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Create an array with 5 dimensions and verify that it has 5 dimensions

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin= 5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


TASK 3

In [29]:
import numpy as np

nilai = np.array(100)
hasil = np.array([1.5,2,'tiga',4,4.5])
objek = np.array([[1.5,3.5,4.5], ['satu', 'dua', 'tiga'], [4, 5, 6]])
item = np.array([[[1.5,3.5,4.5], ['satu', 'dua', 'tiga']], [[4, 5, 6], [7, 13, 15]]])

print(nilai.ndim)
print(hasil.ndim)
print(objek.ndim)
print(item.ndim)

0
1
2
3


In [33]:
import numpy as np

hasil = np.array([1.5,2,'tiga',4,4.5], ndmin= 3)

print(hasil)
print('number of dimensions :', nilai.ndim)

[[['1.5' '2' 'tiga' '4' '4.5']]]
number of dimensions : 0


In [8]:
# Get the first element from the following array

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
# Get the second element from the following array

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
# Get the third element from the following array

In [34]:
import numpy as np

hasil = np.array([1.5,2,'tiga',4,4.5])

print(hasil[2])

tiga


In [ ]:
# Get the third and fourth elements from the following array and add them

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [42]:
import numpy as np

hasil = np.array([2,4,6,8,9,15])

print(hasil[2] + hasil[5])

21


In [ ]:
# Access the element on the first row, second columb

In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
# Access the element on the 2nd row, 5th columb

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


TASK 4

In [17]:
import numpy as np

arr = np.array([[2,3,4,5], [12,13,14,15], [22,23,24,25]]) 

In [18]:
print(arr[0, 1] + arr[1, 2] + arr[2, 3])

42


In [19]:
print ('third element on second row: ', arr[1, 2])

third element on second row:  14
